import type { BookDefinition, EducationItem, ExperienceItem, ProjectItem, SkillGroup } from '../types/content';

export const homeEn = {
  prologue: 'PROLOGUE / 00',
  title: 'The Celestial Archive',
  description:
    'Technology, research and purpose. A collection of chapters built with curiosity, discipline and the decision to always go a little further.',
  cta: 'EXPLORE THE ARCHIVE',
  quote: '“There is always something new to discover.”',
} as const;

export const booksEn: BookDefinition[] = [
  { id: 'about', number: '01', title: 'About', subtitle: 'Story and purpose', tone: 'cream' },
  { id: 'experience', number: '02', title: 'Experience', subtitle: 'Professional journey', tone: 'terracotta' },
  { id: 'projects', number: '03', title: 'Projects', subtitle: 'Ideas I build', tone: 'charcoal' },
  { id: 'skills', number: '04', title: 'Skills', subtitle: 'Knowledge and method', tone: 'sand' },
  { id: 'education', number: '05', title: 'Education', subtitle: 'Learning and discipline', tone: 'copper' },
  { id: 'contact', number: '06', title: 'Contact', subtitle: 'The next chapter', tone: 'brown' },
];

export const aboutEn = {
  chapter: 'CHAPTER I',
  title: 'About me',
  intro:
    'Systems Engineer with a structured, curious and imaginative way of thinking. Technology motivates me because there is always something new to learn, research or solve.',
  second:
    'I prefer to understand a problem deeply, explore alternatives and then build a solution with intention.',
  traits: 'BETWEEN LOGIC AND CONSTELLATIONS',
  traitsBody: 'I observe. I research. I connect ideas. I build.',
  quote: '“I do not follow a map. I learn to read the stars.”',
  quoteBody:
    'Technology is constantly changing. My way forward is to understand, research and build my own path.',
  methodTitle: 'Understand before building',
  method: [
    ['01', 'UNDERSTAND', 'Understand the problem and its context before deciding.'],
    ['02', 'RESEARCH', 'Compare alternatives, risks and possibilities.'],
    ['03', 'ORGANIZE', 'Turn information into a clear and executable plan.'],
    ['04', 'SOLVE', 'Build, test, adjust and learn from the result.'],
  ],
};

export const experienceEn: ExperienceItem[] = [
  {
    period: 'Oct 2025 — Jun 2026',
    role: 'E-Commerce Consultant',
    company: 'Componentes El Orbe',
    focus: 'Technical coordination, IT operations, cybersecurity, AWS, incident management and process improvement.',
    points: [
      'Coordinated cybersecurity, incident and remediation workstreams.',
      'Tracked tasks, defects, findings, blockers and risks with Jira and Xray.',
      'Monitored AWS services and supported operational continuity and escalation.',
      'Performed technical and operational audits aligned with ISO 27001 principles.',
      'Supported SDLC, testing, changes, releases and implementations.',
    ],
    tools: ['Jira', 'Xray', 'AWS', 'ServiceNow', 'ISO 27001', 'SDLC'],
  },
  {
    period: 'Jan 2023 — Dec 2024',
    role: 'Systems Engineer focused on Web Development',
    company: 'Tavuel',
    focus: 'End-to-end web development, maintenance, integrations and change support.',
    points: [
      'Approximately three projects of different sizes, including greenfield, existing and legacy systems.',
      'React and TypeScript on frontend; Node.js/NestJS, REST APIs, GraphQL and Prisma on backend.',
      'Integrations with Google APIs/Maps, Firebase, email, ERP and Costa Rica tax services.',
      'MySQL, SQL Server, MongoDB and Firebase.',
      'Testing, debugging, Git/GitHub, Pull Requests, code review and post-deployment validation.',
    ],
    tools: ['React', 'TypeScript', 'Node.js', 'NestJS', 'SQL', 'Git/GitHub'],
  },
  {
    period: '2019',
    role: 'Technical Support Intern',
    company: 'Clínica UNIBE',
    focus: 'On-site and remote support, hardware, software, networking and operational continuity.',
    points: [],
    tools: ['Windows', 'Networking', 'Hardware'],
  },
  {
    period: '2018',
    role: 'IT Support Intern',
    company: 'Servicio Fitosanitario del Estado',
    focus: 'Network configuration, equipment maintenance, UPS and hardware diagnostics.',
    points: [],
    tools: ['Networking', 'Hardware', 'UPS'],
  },
];

export const projectsIntroEn = {
  chapter: 'CHAPTER III',
  title: 'Cases & Projects',
  lead: 'Not only what I built.\nThe problems I had to understand in order to build it.',
  description:
    'A selection of development, integrations, cloud, cybersecurity and technology management applied to real situations.',
} as const;

export const projectsEn: ProjectItem[] = [
  {
    number: '01',
    title: 'End-to-end sales platform',
    status: 'case',
    group: 'DEVELOPMENT',
    category: 'DEVELOPMENT · FULL STACK · PROFESSIONAL EXPERIENCE',
    summary: 'Development of a sales platform with authentication, administration, analytics, APIs and a complete payment process.',
    context: 'Development of a sales platform covering the complete flow from authentication and user administration to sales processing, analytics and payment gateway.',
    challengeLabel: 'Challenges',
    challenges: [
      'Preserve purchase state during connection loss, page reloads or other interruptions during payment.',
      'Manage sessions and tokens to prevent progress loss during lengthy processes.',
      'Work directly on payment gateway logic.',
      'Create or modify endpoints when needed.',
      'Analyze duplicated or incorrectly implemented endpoints.',
      'Create administrative charts using system data and adapt them to different designs.',
      'Resolve an iOS frontend issue affecting payment functionality.',
      'Adapt email templates for Gmail, Outlook, iOS and other clients.',
      'Support the detection of a database-related issue.',
    ],
    participation: ['Frontend + Backend + APIs + Debugging + Testing + Integrations.'],
    result: 'Critical purchase-flow, authentication and integration issues were resolved, preserving process continuity through payment and the operation of administrative modules.',
    tools: ['React', 'TypeScript', 'Node.js', 'APIs', 'Auth/Tokens', 'Payments', 'SQL', 'Email'],
  },
  {
    number: '02',
    title: 'Accounting system + shared API',
    status: 'case',
    group: 'DEVELOPMENT',
    category: 'DEVELOPMENT · SYSTEM INTEGRATION',
    summary: 'Changes to an accounting system connected to an API shared with a sales application.',
    context: 'An accounting application belonged to an ecosystem where the same API was also used by another sales system.',
    challengeLabel: 'Challenge',
    challenges: ['Modifying the backend required first understanding what each system consumed because one change could affect both projects.'],
    participation: [
      'Review which endpoint the application used.',
      'Analyze dependencies.',
      'Consult the other system’s team when a change could affect it.',
      'Recover context with developers who had previously worked on that area.',
      'Validate behavior after changes.',
      'Participate in reviewing and restructuring duplicated or incorrectly implemented endpoints.',
      'Support the detection of a database-related issue.',
    ],
    process: ['Identify', 'Research', 'Consult', 'Modify', 'Test', 'Validate'],
    flow: ['Accounting system', 'Shared API', 'Sales system'],
    result: 'Changes and corrections were introduced while maintaining control over the dependencies between both systems.',
    tools: ['API'],
  },
  {
    number: '03',
    title: 'Evolution of a legacy sales system',
    status: 'case',
    group: 'DEVELOPMENT',
    category: 'DEVELOPMENT · LEGACY · REFACTORING',
    summary: 'Research, maintenance and evolution of an existing application with shared dependencies.',
    context: 'An existing sales system within the same ecosystem, with prior code and shared dependencies that required research before making changes.',
    challengeLabel: 'Challenge',
    challenges: ['Understand a solution I had not built entirely myself and learn the reasoning behind previous decisions before continuing its development.'],
    participation: [
      'Research existing code.',
      'Understand flows.',
      'Correct functionality.',
      'Refactor code.',
      'Develop new functionality.',
      'Integrate with the shared API.',
      'Validate changes to avoid affecting the other system.',
      'Debug and test.',
    ],
    result: 'The system continued evolving while remaining compatible with existing dependencies.',
    tools: ['APIs', 'Backend', 'Frontend', 'Refactoring', 'Debugging', 'Testing'],
  },
  {
    number: '04',
    title: 'AWS infrastructure remediation',
    status: 'case',
    group: 'CLOUD & CYBERSECURITY',
    category: 'CLOUD · CYBERSECURITY · COORDINATION',
    summary: 'Investigation and follow-up of a persistent vulnerability related to an AMI and AWS instances.',
    subtitle: 'A persistent vulnerability that required looking beyond the alert.',
    context: 'Monitoring repeatedly surfaced a high-severity vulnerability associated with AWS infrastructure. Although the finding had been known for some time and was considered limited in impact, the analysis went deeper because it conflicted with internal policies.',
    challengeLabel: 'Finding',
    challenges: [
      'Brinqa and AWS analysis showed that a cloned AMI inherited a condition that did not align with company policies.',
      'When new instances were created from that image, the problematic condition was reproduced.',
      'The behavior of related elastic instances was also analyzed.',
    ],
    participation: [
      'Detect and report the issue again.',
      'Analyze information in Brinqa and AWS.',
      'Gather evidence and tests.',
      'Document observed behavior.',
      'Create and follow up on tickets.',
      'Coordinate meetings.',
      'Follow up with infrastructure and development.',
      'Support planning, implementation and validation.',
      'Contribute criteria to economic analysis when inconsistencies appeared.',
      'Verify the outcome before closure.',
    ],
    result: 'The involved elastic instances were removed and the AMI was adapted to the relevant policies. The process was completed successfully and prepared to continue with the next team.',
    tools: ['AWS', 'Brinqa', 'Jira', 'Vulnerability Management'],
  },
  {
    number: '05',
    title: 'Vulnerability management',
    status: 'case',
    group: 'CLOUD & CYBERSECURITY',
    category: 'CYBERSECURITY · OPERATIONS',
    summary: 'Analysis, follow-up and validation of vulnerabilities from detection through closure.',
    context: 'Continuous review of vulnerabilities mainly related to versions, updates and configuration.',
    challengeLabel: 'Challenge',
    challenges: [],
    participation: [
      'Analyze each finding.',
      'Compare Brinqa data against infrastructure evidence.',
      'Review AWS information.',
      'Determine whether the behavior represented a real vulnerability or a possible false positive.',
      'Follow up with the responsible team.',
      'Review evidence delivered by infrastructure.',
      'Analyze the explanation documented in the ticket.',
      'Recheck the finding’s status afterward.',
      'Make the closure decision based on evidence and the correction performed.',
    ],
    process: ['Brinqa', 'Finding review', 'AWS / Infrastructure', 'Real or false positive', 'Ticket + evidence', 'Remediation', 'Validation', 'Closure'],
    result: 'Cases were supported from analysis through post-remediation validation, confirming that the finding was no longer active before closure.',
    tools: ['Brinqa', 'AWS', 'Jira', 'Vulnerability Management'],
  },
  {
    number: '06',
    title: 'Multinational registration & OTP',
    status: 'case',
    group: 'TECHNOLOGY MANAGEMENT',
    category: 'TECHNOLOGY MANAGEMENT · QA · INTEGRATIONS',
    summary: 'Analysis and validation of a registration and OTP flow for the Dominican Republic and Guatemala.',
    metaLabel: 'Markets',
    meta: 'Dominican Republic · Guatemala',
    context: 'A web ecosystem required users to request an OTP before completing registration.',
    challengeLabel: 'Problem',
    challenges: [
      'Behavior was inconsistent between the Dominican Republic and Guatemala.',
      'In Guatemala, a communication/delivery issue affected OTP transfer between integrated systems.',
      'Without an OTP, a new customer could not complete registration.',
    ],
    flow: ['User', 'Web', 'Registration API', 'Delivery service/API', 'OTP', 'Registration'],
    participation: [
      'Analyze the different parts of the ecosystem.',
      'Review the web system.',
      'Compare implementation against documentation.',
      'Identify differences and elements requiring review.',
      'Run OTP tests in both countries.',
      'Document findings.',
      'Communicate results.',
      'Coordinate with web development.',
      'Coordinate with the team responsible for the integrated API.',
      'Support corrections.',
      'Perform final functional validation.',
    ],
    result: 'After corrections and testing, the flow was validated and approved for production release.',
    tools: ['QA', 'APIs', 'OTP'],
  },
  {
    number: '07',
    title: 'Technology ecosystem mapping',
    status: 'case',
    group: 'TECHNOLOGY MANAGEMENT',
    category: 'MANAGEMENT · ANALYSIS · DOCUMENTATION',
    summary: 'First phase of organizing and documenting systems and issues across an enterprise ecosystem.',
    context: 'Participation in the first phase of an initiative to map systems and issues within an enterprise technology ecosystem.',
    challengeLabel: 'Challenge',
    challenges: [],
    participation: [
      'Understand and organize the participant schedule.',
      'Follow up on availability and progress.',
      'Coordinate the first meetings related to priority mappings.',
      'Record responses and issues.',
      'Resolve questions when appropriate.',
      'Document information in Confluence.',
      'Work with related diagrams.',
      'Organize the information gathered.',
      'Create a statistics/metrics table to analyze projects according to their issues.',
    ],
    result: 'The first stage was organized with initial meetings coordinated, responses documented by issue and a metrics structure available for continued analysis.',
    tools: ['Confluence', 'Documentation', 'Diagrams', 'Coordination', 'Metrics'],
  },
  {
    number: '02',
    title: 'Cyber Risk Intelligence',
    status: 'planned',
    stack: ['Power BI', 'Python', 'Cybersecurity'],
    description: 'Portfolio project — planned.',
  },
  {
    number: '03',
    title: 'Data & BI',
    status: 'planned',
    stack: ['Power BI', 'Analytics'],
    description: 'Portfolio project — planned.',
  },
  {
    number: '04',
    title: 'Applied Security',
    status: 'planned',
    stack: ['Cybersecurity', 'Research'],
    description: 'Portfolio project — planned.',
  },
];

export const skillsEn: SkillGroup[] = [
  { title: 'Frontend', level: 'professional', items: ['React', 'TypeScript', 'JavaScript', 'HTML5', 'CSS3', 'SASS/SCSS', 'Responsive', 'Bootstrap', 'Tailwind', 'Material'] },
  { title: 'Backend & APIs', level: 'professional', items: ['Node.js', 'NestJS', 'REST APIs', 'GraphQL', 'Prisma', 'Validation', 'Versioning', 'Error handling'] },
  { title: 'Data', level: 'professional', items: ['MySQL', 'SQL Server', 'MongoDB', 'Firebase', 'SQL', 'JOINs', 'Subqueries', 'CRUD', 'Data modeling'] },
  { title: 'Project & Delivery', level: 'professional', items: ['Jira', 'Xray', 'ServiceNow', 'Scrum', 'Agile', 'SDLC', 'Incident Management', 'Reporting', 'Stakeholders'] },
  { title: 'Cloud & Operations', level: 'professional', items: ['AWS Monitoring', 'AWS Lambda reviews', 'Troubleshooting', 'Windows', 'Linux', 'Networking'] },
  { title: 'Cybersecurity', level: 'practical', items: ['Vulnerability review', 'ISO 27001', 'OWASP Top 10', 'Basic IAM', 'Authentication', 'Tokens', 'Sessions', 'Encryption'] },
  { title: 'Data & BI', level: 'practical', items: ['Power BI Level I', 'Power BI Level II', 'Data analysis'] },
  { title: 'Complementary training', level: 'complementary', items: ['Ethical Hacking', 'Cryptography', 'Cybersecurity Principles', 'GitHub Actions', 'CI/CD concepts'] },
];

export const educationEn: EducationItem[] = [
  { title: 'Information Systems Engineering', institution: 'Universidad Internacional de las Américas (UIA)', year: '2025', note: 'Cum Laude with Honors' },
  { title: 'Cybersecurity Specialization', institution: 'Universidad Fidélitas', year: '2025', note: '96 hours' },
  { title: 'Data Analysis with Power BI — Level II', institution: 'Universidad de Costa Rica (UCR)', year: '2025' },
  { title: 'Data Analysis with Power BI — Level I', institution: 'Universidad de Costa Rica (UCR)', year: '2025' },
  { title: 'Technical High School Diploma in IT Support', institution: 'Colegio Técnico Profesional de Pavas', year: '2019' },
];

export const certificationsEn = [
  'Scrum Fundamentals Certified — VMEdu · 2022',
  'React Development — Udemy · 2023',
  'Professional Communication in English — Rocket Girls · 2025',
  'Advanced Conversational English — Academia Europea · 2021',
  'Ethical Hacking — Universidad Fidélitas · 2025',
  'Cryptography — Universidad Fidélitas · 2025',
  'Cybersecurity Principles — Universidad Fidélitas · 2025',
];
