import type { BookDefinition, EducationItem, ExperienceItem, ProjectItem, SkillGroup } from '../types/content';

export const homeEn = {
  prologue: 'PROLOGUE / 00',
  title: 'Digital Archive · Sara Retana',
  description:
    'Technology, research and purpose. A collection of chapters built with curiosity, discipline and the decision to always go a little further.',
  cta: 'EXPLORE THE ARCHIVE',
  quote: '“There is always something new to discover.”',
} as const;

export const booksEn: BookDefinition[] = [
  { id: 'about', number: '01', title: 'About', subtitle: 'Story and purpose', tone: 'cream' },
  { id: 'experience', number: '02', title: 'Experience', subtitle: 'Professional journey', tone: 'terracotta' },
  { id: 'projects', number: '03', title: 'Projects', subtitle: 'Ideas I build', tone: 'charcoal' },
  { id: 'skills', number: '04', title: 'Skills', subtitle: 'Knowledge and method', tone: 'sand' },
  { id: 'education', number: '05', title: 'Education', subtitle: 'Learning and discipline', tone: 'copper' },
  { id: 'contact', number: '06', title: 'Contact', subtitle: 'The next chapter', tone: 'brown' },
];

export const aboutEn = {
  chapter: 'CHAPTER I',
  title: 'About me',
  intro:
    'Systems Engineer with a structured, curious and imaginative way of thinking. Technology motivates me because there is always something new to learn, research or solve.',
  second:
    'I prefer to understand a problem deeply, explore alternatives and then build a solution with intention.',
  traits: 'BETWEEN LOGIC AND CONSTELLATIONS',
  traitsBody: 'I observe. I research. I connect ideas. I build.',
  quote: '“I do not follow a map. I learn to read the stars.”',
  quoteBody:
    'Technology is constantly changing. My way forward is to understand, research and build my own path.',
  methodTitle: 'Understand before building',
  method: [
    ['01', 'UNDERSTAND', 'Understand the problem and its context before deciding.'],
    ['02', 'RESEARCH', 'Compare alternatives, risks and possibilities.'],
    ['03', 'ORGANIZE', 'Turn information into a clear and executable plan.'],
    ['04', 'SOLVE', 'Build, test, adjust and learn from the result.'],
  ],
};

export const experienceEn: ExperienceItem[] = [
  {
    period: 'Oct 2025 — Jun 2026',
    role: 'E-Commerce Consultant',
    company: 'Componentes El Orbe',
    client: 'Philip Morris International',
    focus: 'Operational ownership of a regional technical operation, coordinating distributed teams, priorities, SLAs, KPIs, vulnerabilities, incidents, changes, third parties and escalations through validation or closure.',
    indicators: [
      { value: '12', label: 'specialists coordinated' },
      { value: '5+', label: 'countries · regional scope' },
      { value: '300–400 → ~1', label: 'findings in high-volume cycles' },
      { value: 'EN / ES', label: 'international coordination' },
    ],
    points: [
      'I coordinated 12 CLOC specialists and maintained continuity across shifts.',
      'I oversaw SLAs, KPIs, priorities, blockers and escalations.',
      'I coordinated incidents, changes, releases and validation with internal and third-party teams.',
      'I reported progress, risks and initiatives to stakeholders.',
    ],
    results: [
      'I recovered and strengthened the weekly remediation plan.',
      'I reduced cycles from approximately 300–400 findings to around 1 weekly pending item.',
      'I coordinated the AMI remediation through removal of the persistent finding.',
      'I centralized ownership, metrics and traceability in Confluence and Jira.',
    ],
    caseNumbers: ['04', '05', '06', '07'],
    kind: 'primary',
    tools: ['Jira', 'Confluence', 'Brinqa', 'AWS', 'ServiceNow', 'ISO 27001'],
  },
  {
    period: 'Jan 2023 — Dec 2024',
    role: 'Systems Engineer focused on Web Development',
    company: 'Tavuel',
    focus: 'End-to-end ownership of frontend and backend functionality, integrations, APIs and the evolution of greenfield, existing and legacy systems, from investigation through post-deployment validation.',
    points: [
      'I developed frontend and backend functionality across three projects.',
      'I resolved purchase, authentication, payment and integration issues.',
      'I analyzed dependencies before modifying APIs and databases.',
      'I validated changes through debugging, testing and code review.',
    ],
    results: [
      'I restored critical purchase and authentication flows.',
      'I corrected integrations without affecting related systems.',
      'I evolved a legacy system while preserving compatibility.',
    ],
    caseNumbers: ['01', '02', '03'],
    kind: 'primary',
    tools: ['React', 'TypeScript', 'Node.js', 'NestJS', 'SQL', 'Git/GitHub'],
  },
  {
    period: '2019',
    role: 'Technical Support Intern',
    company: 'Clínica UNIBE',
    focus: 'On-site and remote support, hardware, software, networking and operational continuity.',
    points: [
      'On-site and remote technical support.',
      'Operational continuity for workstations.',
      'Configuration and maintenance of equipment and network devices.',
      'Support for basic hardware and software incidents.',
    ],
    results: [
      'Support incidents resolved and operational assistance provided to users.',
      'Workstations, equipment and network devices configured and maintained.',
    ],
    kind: 'internship',
    tools: ['Windows', 'Networking', 'Hardware'],
  },
  {
    period: '2018',
    role: 'IT Support Intern',
    company: 'Servicio Fitosanitario del Estado',
    focus: 'Network configuration, equipment maintenance, UPS and hardware diagnostics.',
    points: [
      'Network configuration and documentation.',
      'Environment and equipment preparation.',
      'Hardware diagnostics and UPS maintenance.',
      'Basic infrastructure support.',
    ],
    results: [
      'Configurations documented and equipment prepared for operation.',
      'Faults diagnosed, UPS units maintained and components replaced.',
    ],
    kind: 'internship',
    tools: ['Networking', 'Hardware', 'UPS'],
  },
];

export const projectsIntroEn = {
  chapter: 'CHAPTER III',
  title: 'Projects',
  lead: 'Ideas I can build, document and share.',
  description:
    'This archive brings together personal and public projects created to explore technologies, solve problems and demonstrate solutions openly.',
} as const;

export const projectsEn: ProjectItem[] = [
  {
    number: '01',
    title: 'End-to-end sales platform',
    status: 'case',
    group: 'DEVELOPMENT',
    category: 'DEVELOPMENT · FULL STACK · PROFESSIONAL EXPERIENCE',
    summary: 'Development of a sales platform with authentication, administration, analytics, APIs and a complete payment process.',
    context: 'Development of a sales platform covering the complete flow from authentication and user administration to sales processing, analytics and payment gateway.',
    challengeLabel: 'Challenges',
    challenges: [
      'Preserve purchase state during connection loss, page reloads or other interruptions during payment.',
      'Manage sessions and tokens to prevent progress loss during lengthy processes.',
      'Work directly on payment gateway logic.',
      'Create or modify endpoints when needed.',
      'Analyze duplicated or incorrectly implemented endpoints.',
      'Create administrative charts using system data and adapt them to different designs.',
      'Resolve an iOS frontend issue affecting payment functionality.',
      'Adapt email templates for Gmail, Outlook, iOS and other clients.',
      'Support the detection of a database-related issue.',
    ],
    participation: ['Frontend + Backend + APIs + Debugging + Testing + Integrations.'],
    result: 'Critical purchase-flow, authentication and integration issues were resolved, preserving process continuity through payment and the operation of administrative modules.',
    tools: ['React', 'TypeScript', 'Node.js', 'APIs', 'Auth/Tokens', 'Payments', 'SQL', 'Email'],
  },
  {
    number: '02',
    title: 'Accounting system + shared API',
    status: 'case',
    group: 'DEVELOPMENT',
    category: 'DEVELOPMENT · SYSTEM INTEGRATION',
    summary: 'Changes to an accounting system connected to an API shared with a sales application.',
    context: 'An accounting application belonged to an ecosystem where the same API was also used by another sales system.',
    challengeLabel: 'Challenge',
    challenges: ['Modifying the backend required first understanding what each system consumed because one change could affect both projects.'],
    participation: [
      'Review which endpoint the application used.',
      'Analyze dependencies.',
      'Consult the other system’s team when a change could affect it.',
      'Recover context with developers who had previously worked on that area.',
      'Validate behavior after changes.',
      'Participate in reviewing and restructuring duplicated or incorrectly implemented endpoints.',
      'Support the detection of a database-related issue.',
    ],
    process: ['Identify', 'Research', 'Consult', 'Modify', 'Test', 'Validate'],
    flow: ['Accounting system', 'Shared API', 'Sales system'],
    result: 'Changes and corrections were introduced while maintaining control over the dependencies between both systems.',
    tools: ['API'],
  },
  {
    number: '03',
    title: 'Evolution of a legacy sales system',
    status: 'case',
    group: 'DEVELOPMENT',
    category: 'DEVELOPMENT · LEGACY · REFACTORING',
    summary: 'Research, maintenance and evolution of an existing application with shared dependencies.',
    context: 'An existing sales system within the same ecosystem, with prior code and shared dependencies that required research before making changes.',
    challengeLabel: 'Challenge',
    challenges: ['Understand a solution I had not built entirely myself and learn the reasoning behind previous decisions before continuing its development.'],
    participation: [
      'Research existing code.',
      'Understand flows.',
      'Correct functionality.',
      'Refactor code.',
      'Develop new functionality.',
      'Integrate with the shared API.',
      'Validate changes to avoid affecting the other system.',
      'Debug and test.',
    ],
    result: 'The system continued evolving while remaining compatible with existing dependencies.',
    tools: ['APIs', 'Backend', 'Frontend', 'Refactoring', 'Debugging', 'Testing'],
  },
  {
    number: '04',
    title: 'AWS infrastructure remediation',
    status: 'case',
    group: 'CLOUD & CYBERSECURITY',
    category: 'CLOUD · CYBERSECURITY · COORDINATION',
    summary: 'Operational ownership and coordination of the remediation of a persistent finding related to an AMI and AWS instances.',
    subtitle: 'A persistent vulnerability that required looking beyond the alert.',
    context: 'A high-severity finding associated with a cloned AMI and the AWS instances created from it remained open within the weekly vulnerability cycle. The condition was reproduced and conflicted with internal policies.',
    objective: 'Remove the persistent finding while maintaining control over the change impact across Infrastructure, CLOC, ServiceNow and the other teams involved.',
    scope: [
      'Own operational follow-through, prioritization, escalation and validation of the case without implying individual execution of every infrastructure change.',
      'Keep ownership, evidence, dependencies, policies, risks and change steps traceable through closure.',
    ],
    strategy: [
      'Correlate Brinqa and AWS evidence to locate the condition inherited through the AMI.',
      'Coordinate impact analysis, change planning, remediation and post-change verification.',
      'Manage the ticket, blockers, evidence and approvals until the finding was confirmed inactive.',
    ],
    coordination: ['CLOC team', 'Infrastructure', 'ServiceNow', 'Information Security', 'Development'],
    challengeLabel: 'Finding',
    challenges: [
      'Brinqa and AWS analysis showed that a cloned AMI inherited a condition that did not align with company policies.',
      'When new instances were created from that image, the problematic condition was reproduced.',
      'The behavior of related elastic instances was also analyzed.',
    ],
    participation: ['Operational coordination, prioritization, escalation, evidence management and remediation validation.'],
    result: 'The AMI was aligned with the relevant policies and the affected elastic instances were removed. After validation, the final persistent finding reached 0 and the case could be closed.',
    tools: ['AWS', 'Brinqa', 'Jira', 'ServiceNow', 'Vulnerability Management'],
  },
  {
    number: '05',
    title: 'Vulnerability management',
    status: 'case',
    group: 'CLOUD & CYBERSECURITY',
    category: 'CYBERSECURITY · OPERATIONS',
    summary: 'Management of the weekly vulnerability cycle across SLAs, severity, environments, remediation, evidence and closure.',
    context: 'Brinqa ran scans throughout the week and generated findings of varying severity across QA, production and other environments. During high-volume periods, a cycle could begin with approximately 300–400 vulnerabilities.',
    objective: 'Classify, prioritize and drive the relevant remediations to resolution before Friday weekly close whenever possible within the established SLA.',
    scope: [
      'Oversee open and closed vulnerabilities, severity, environment, risk, weekly compliance, SLAs and KPIs.',
      'Operationally manage an approximately 12-person CLOC specialist team, distributing priorities and escalating blockers or dependencies.',
    ],
    strategy: [
      'Recover a remediation plan that had lost continuity and incorporate feedback from the CLOC team.',
      'Establish weekly coordination from Monday onward, prioritizing changes according to risk and environment.',
      'Correlate Brinqa, AWS and Infrastructure evidence before validating remediation or ruling out a false positive.',
      'Coordinate a remediation process that incorporated AWS Lambda automation for recurring updates.',
    ],
    coordination: ['CLOC', 'Infrastructure', 'Information Security', 'ServiceNow', 'Technical owners based on each finding'],
    challengeLabel: 'Challenge',
    challenges: [],
    participation: ['Weekly management of priorities, ownership, SLAs, evidence, escalations, validation and closure.'],
    process: ['Brinqa', 'Finding review', 'AWS / Infrastructure', 'Real or false positive', 'Ticket + evidence', 'Remediation', 'Validation', 'Closure'],
    result: 'During high-volume periods, cycles started with approximately 300–400 findings and typically reached around 1 pending item by weekly close. Every closure was validated through evidence and a post-remediation check confirming that the finding was no longer active.',
    tools: ['Brinqa', 'AWS', 'AWS Lambda', 'Jira', 'ServiceNow', 'Vulnerability Management'],
  },
  {
    number: '06',
    title: 'Multinational registration & OTP',
    status: 'case',
    group: 'TECHNOLOGY MANAGEMENT',
    category: 'TECHNOLOGY MANAGEMENT · QA · INTEGRATIONS',
    summary: 'Analysis and validation of a registration and OTP flow for the Dominican Republic and Guatemala.',
    metaLabel: 'Markets',
    meta: 'Dominican Republic · Guatemala',
    context: 'A web ecosystem required users to request an OTP before completing registration.',
    objective: 'Restore and validate the registration and OTP flow for the Dominican Republic and Guatemala through production approval.',
    scope: [
      'Coordinate troubleshooting, testing, defects, blockers, corrections and validation across distributed systems and teams.',
      'Maintain ownership of technical follow-through through final flow approval.',
    ],
    strategy: [
      'Compare implementation against documentation and test OTP behavior in both markets.',
      'Isolate differences across the web application, registration API and delivery service; document findings and coordinate corrections.',
      'Perform final functional validation after the changes.',
    ],
    coordination: ['Web development', 'Business', 'Dominican Republic and Guatemala teams', 'Third-party developers in the Philippines · technical coordination in English'],
    challengeLabel: 'Problem',
    challenges: [
      'Behavior was inconsistent between the Dominican Republic and Guatemala.',
      'In Guatemala, a communication/delivery issue affected OTP transfer between integrated systems.',
      'Without an OTP, a new customer could not complete registration.',
    ],
    flow: ['User', 'Web', 'Registration API', 'Delivery service/API', 'OTP', 'Registration'],
    participation: ['International coordination, testing, troubleshooting, third-party management and follow-through to production.'],
    result: 'After corrections and testing, the flow was validated and approved for production release.',
    tools: ['QA', 'APIs', 'OTP', 'Jira', 'English technical communication'],
  },
  {
    number: '07',
    title: 'Technology ecosystem mapping',
    status: 'case',
    group: 'TECHNOLOGY MANAGEMENT',
    category: 'MANAGEMENT · ANALYSIS · DOCUMENTATION',
    summary: 'Structuring the first phase of a technology mapping initiative to establish visibility, continuity and prioritization criteria.',
    context: 'A technology mapping initiative needed to recover visibility across projects, systems, owners, dependencies and issues distributed among multiple teams.',
    objective: 'Turn fragmented information into a centralized, usable foundation for continuity, analysis and decision-making.',
    scope: [
      'Structure the first phase, coordinate owners and establish follow-through without claiming individual leadership of every meeting.',
      'Provide stakeholders with visibility into progress, risks, blockers and initiative status.',
    ],
    strategy: [
      'Consolidate owners, communication channels, dependencies, issues and documentation in Confluence.',
      'Associate diagrams and organize information by project or system.',
      'Create a scale and metrics model to analyze, compare and prioritize initiatives according to their issues.',
    ],
    coordination: ['Project and system owners', 'Technical teams', 'Stakeholders', 'Operational supervision'],
    challengeLabel: 'Challenge',
    challenges: [],
    participation: ['Process structuring, owner coordination, centralized documentation and metrics-model design.'],
    result: 'The first phase was structured with projects and systems documented, owners and channels defined, issues centralized, diagrams associated and a metrics model available for continued analysis and prioritization.',
    tools: ['Confluence', 'Jira', 'Documentation', 'Diagrams', 'Coordination', 'Metrics'],
  },
  {
    number: '02',
    title: 'Cyber Risk Intelligence',
    status: 'planned',
    stack: ['Power BI', 'Python', 'Cybersecurity'],
    description: 'Portfolio project — planned.',
  },
  {
    number: '03',
    title: 'Data & BI',
    status: 'planned',
    stack: ['Power BI', 'Analytics'],
    description: 'Portfolio project — planned.',
  },
  {
    number: '04',
    title: 'Applied Security',
    status: 'planned',
    stack: ['Cybersecurity', 'Research'],
    description: 'Portfolio project — planned.',
  },
];

export const skillsEn: SkillGroup[] = [
  { title: 'Frontend', level: 'professional', items: ['React', 'TypeScript', 'JavaScript', 'HTML5', 'CSS3', 'SASS/SCSS', 'Responsive', 'Bootstrap', 'Tailwind', 'Material'] },
  { title: 'Backend & APIs', level: 'professional', items: ['Node.js', 'NestJS', 'REST APIs', 'GraphQL', 'Prisma', 'Validation', 'Versioning', 'Error handling'] },
  { title: 'Data', level: 'professional', items: ['MySQL', 'SQL Server', 'MongoDB', 'Firebase', 'SQL', 'JOINs', 'Subqueries', 'CRUD', 'Data modeling'] },
  { title: 'Project & Delivery', level: 'professional', items: ['Jira', 'Xray', 'ServiceNow', 'Scrum', 'Agile', 'SDLC', 'Incident Management', 'Reporting', 'Stakeholders'] },
  { title: 'Cloud & Operations', level: 'professional', items: ['AWS Monitoring', 'AWS Lambda reviews', 'Troubleshooting', 'Windows', 'Linux', 'Networking'] },
  { title: 'Cybersecurity', level: 'practical', items: ['Vulnerability review', 'ISO 27001', 'OWASP Top 10', 'Basic IAM', 'Authentication', 'Tokens', 'Sessions', 'Encryption'] },
  { title: 'Data & BI', level: 'practical', items: ['Power BI Level I', 'Power BI Level II', 'Data analysis'] },
  { title: 'Complementary training', level: 'complementary', items: ['Ethical Hacking', 'Cryptography', 'Cybersecurity Principles', 'GitHub Actions', 'CI/CD concepts'] },
];

export const educationEn: EducationItem[] = [
  { title: 'Information Systems Engineering', institution: 'Universidad Internacional de las Américas (UIA)', year: '2025', note: 'Cum Laude with Honors' },
  { title: 'Cybersecurity Specialization', institution: 'Universidad Fidélitas', year: '2025', note: '96 hours' },
  { title: 'Data Analysis with Power BI — Level II', institution: 'Universidad de Costa Rica (UCR)', year: '2025' },
  { title: 'Data Analysis with Power BI — Level I', institution: 'Universidad de Costa Rica (UCR)', year: '2025' },
  { title: 'Technical High School Diploma in IT Support', institution: 'Colegio Técnico Profesional de Pavas', year: '2019' },
];

export const certificationsEn = [
  'Scrum Fundamentals Certified — VMEdu · 2022',
  'React Development — Udemy · 2023',
  'Professional Communication in English — Rocket Girls · 2025',
  'Advanced Conversational English — Academia Europea · 2021',
  'Ethical Hacking — Universidad Fidélitas · 2025',
  'Cryptography — Universidad Fidélitas · 2025',
  'Cybersecurity Principles — Universidad Fidélitas · 2025',
];
