import type { BookDefinition, EducationItem, ExperienceItem, ProjectItem, SkillGroup } from '../types/content';

export const homeEs = {
  prologue: 'PRÓLOGO / 00',
  title: 'Digital Archive · Sara Retana',
  description:
    'Tecnología, investigación y propósito. Una colección de capítulos construidos con curiosidad, disciplina y la decisión de ir siempre un poco más allá.',
  cta: 'EXPLORAR EL ARCHIVO',
  quote: '“Siempre hay algo nuevo que descubrir.”',
} as const;

export const booksEs: BookDefinition[] = [
  { id: 'about', number: '01', title: 'Sobre mí', subtitle: 'Historia y propósito', tone: 'cream' },
  { id: 'experience', number: '02', title: 'Experiencia', subtitle: 'Trayectoria profesional', tone: 'terracotta' },
  { id: 'projects', number: '03', title: 'Proyectos', subtitle: 'Ideas que construyo', tone: 'charcoal' },
  { id: 'skills', number: '04', title: 'Habilidades', subtitle: 'Conocimiento y método', tone: 'sand' },
  { id: 'education', number: '05', title: 'Formación', subtitle: 'Aprendizaje y disciplina', tone: 'copper' },
  { id: 'contact', number: '06', title: 'Contacto', subtitle: 'El siguiente capítulo', tone: 'brown' },
];

export const aboutEs = {
  chapter: 'CAPÍTULO I',
  title: 'Sobre mí',
  intro:
    'Ingeniera en Sistemas con una forma de pensar estructurada, curiosa e imaginativa. Me motiva la tecnología porque siempre hay algo nuevo que aprender, investigar o resolver.',
  second:
    'Prefiero entender un problema a fondo, explorar alternativas y después construir una solución con intención.',
  traits: 'ENTRE LÓGICA Y CONSTELACIONES',
  traitsBody: 'Observo. Investigo. Conecto ideas. Construyo.',
  quote: '“No sigo un mapa. Aprendo a leer las estrellas.”',
  quoteBody:
    'La tecnología cambia constantemente. Mi forma de avanzar es entender, investigar y construir mi propio camino.',
  methodTitle: 'Entender antes de construir',
  method: [
    ['01', 'ENTENDER', 'Comprender el problema y el contexto antes de decidir.'],
    ['02', 'INVESTIGAR', 'Comparar alternativas, riesgos y posibilidades.'],
    ['03', 'ORGANIZAR', 'Transformar información en un plan claro y ejecutable.'],
    ['04', 'RESOLVER', 'Construir, probar, ajustar y aprender del resultado.'],
  ],
};

export const experienceEs: ExperienceItem[] = [
  {
    period: 'Oct 2025 — Jun 2026',
    role: 'Consultora E-Commerce',
    company: 'Componentes El Orbe',
    client: 'Philip Morris International',
    focus: 'Responsabilidad operativa sobre una operación técnica regional: coordinación de equipos distribuidos, prioridades, SLA, KPIs, vulnerabilidades, incidentes, cambios, terceros y escalaciones hasta validación o cierre.',
    indicators: [
      { value: '12', label: 'especialistas coordinados' },
      { value: '5+', label: 'países · alcance regional' },
      { value: '300–400 → ~1', label: 'hallazgos en ciclos de alto volumen' },
      { value: 'ES / EN', label: 'coordinación internacional' },
    ],
    points: [
      'Coordiné 12 especialistas CLOC y aseguré continuidad entre turnos.',
      'Supervisé SLA, KPIs, prioridades, bloqueos y escalaciones.',
      'Coordiné incidentes, cambios, releases y validaciones con equipos internos y terceros.',
      'Reporté avances, riesgos e iniciativas a stakeholders.',
    ],
    results: [
      'Recuperé y fortalecí el plan semanal de remediación.',
      'Reduje ciclos de aproximadamente 300–400 hallazgos a alrededor de 1 pendiente semanal.',
      'Coordiné la remediación del AMI hasta eliminar el hallazgo persistente.',
      'Centralicé responsables, métricas y trazabilidad en Confluence y Jira.',
    ],
    caseNumbers: ['04', '05', '06', '07'],
    kind: 'primary',
    tools: ['Jira', 'Confluence', 'Brinqa', 'AWS', 'ServiceNow', 'ISO 27001'],
  },
  {
    period: 'Ene 2023 — Dic 2024',
    role: 'Ingeniera en Sistemas enfocada en Desarrollo Web',
    company: 'Tavuel',
    focus: 'Responsabilidad end-to-end sobre funcionalidades frontend y backend, integraciones, APIs y evolución de sistemas nuevos, existentes y legados, desde la investigación hasta la validación posterior al deployment.',
    points: [
      'Desarrollé funcionalidades frontend y backend en tres proyectos.',
      'Resolví problemas de compra, autenticación, pagos e integraciones.',
      'Analicé dependencias antes de modificar APIs y bases de datos.',
      'Validé cambios mediante debugging, testing y code review.',
    ],
    results: [
      'Restablecí flujos críticos de compra y autenticación.',
      'Corregí integraciones sin afectar sistemas relacionados.',
      'Evolucioné un sistema legado manteniendo su compatibilidad.',
    ],
    caseNumbers: ['01', '02', '03'],
    kind: 'primary',
    tools: ['React', 'TypeScript', 'Node.js', 'NestJS', 'SQL', 'Git/GitHub'],
  },
  {
    period: '2019',
    role: 'Pasante de Soporte Técnico',
    company: 'Clínica UNIBE',
    focus: 'Soporte presencial y remoto, hardware, software, red y continuidad operativa.',
    points: [
      'Soporte técnico presencial y remoto.',
      'Continuidad operativa de estaciones de trabajo.',
      'Configuración y mantenimiento de equipos y dispositivos de red.',
      'Atención de incidentes básicos de hardware y software.',
    ],
    results: [
      'Resolución de incidentes de soporte y apoyo operativo a usuarios.',
      'Configuración y mantenimiento de estaciones de trabajo, equipos y red.',
    ],
    kind: 'internship',
    tools: ['Windows', 'Networking', 'Hardware'],
  },
  {
    period: '2018',
    role: 'Pasante de Soporte TI',
    company: 'Servicio Fitosanitario del Estado',
    focus: 'Configuración de red, mantenimiento de equipos, UPS y diagnóstico de hardware.',
    points: [
      'Configuración y documentación de red.',
      'Preparación de ambientes y equipos.',
      'Diagnóstico de hardware y mantenimiento de UPS.',
      'Soporte de infraestructura básica.',
    ],
    results: [
      'Documentación de configuraciones y preparación operativa de equipos.',
      'Diagnóstico de fallas, mantenimiento de UPS y reemplazo de componentes.',
    ],
    kind: 'internship',
    tools: ['Networking', 'Hardware', 'UPS'],
  },
];

export const projectsIntroEs = {
  chapter: 'CAPÍTULO III',
  title: 'Proyectos',
  lead: 'Ideas que puedo construir, documentar y compartir.',
  description:
    'Este archivo reúne proyectos personales y públicos creados para explorar tecnologías, resolver problemas y demostrar soluciones de forma abierta.',
} as const;

export const projectsEs: ProjectItem[] = [
  {
    number: '01',
    title: 'Plataforma de ventas end-to-end',
    status: 'case',
    group: 'DESARROLLO',
    category: 'DESARROLLO · FULL STACK · EXPERIENCIA PROFESIONAL',
    summary: 'Desarrollo de una plataforma de ventas con autenticación, administración, estadísticas, APIs y proceso completo de pago.',
    context: 'Desarrollo de una plataforma de ventas con flujo completo desde autenticación y administración de usuarios hasta procesamiento de ventas, estadísticas y pasarela de pago.',
    challengeLabel: 'Desafíos',
    challenges: [
      'Mantener el estado de una compra ante pérdida de conexión, recarga de página u otras interrupciones durante el pago.',
      'Controlar sesión y tokens para evitar pérdida de progreso durante procesos extensos.',
      'Trabajar directamente en la lógica de la pasarela de pago.',
      'Crear o modificar endpoints cuando era necesario.',
      'Analizar endpoints duplicados o incorrectamente implementados.',
      'Crear gráficos administrativos utilizando información del sistema y adaptarlos a diferentes diseños.',
      'Resolver un problema de frontend en iOS que afectaba una funcionalidad del pago.',
      'Adaptar plantillas de correo para Gmail, Outlook, iOS y otros clientes.',
      'Apoyar la detección de un problema relacionado con base de datos.',
    ],
    participation: ['Frontend + Backend + APIs + Debugging + Testing + Integraciones.'],
    result: 'Se resolvieron problemas críticos del flujo de compra, autenticación e integración, permitiendo mantener la continuidad del proceso hasta el pago y la operación de los módulos administrativos.',
    tools: ['React', 'TypeScript', 'Node.js', 'APIs', 'Auth/Tokens', 'Payments', 'SQL', 'Email'],
  },
  {
    number: '02',
    title: 'Sistema contable + API compartida',
    status: 'case',
    group: 'DESARROLLO',
    category: 'DESARROLLO · INTEGRACIÓN DE SISTEMAS',
    summary: 'Cambios en un sistema contable conectado a una API compartida con una aplicación de ventas.',
    context: 'Una aplicación contable pertenecía a un ecosistema donde una misma API también era utilizada por otro sistema de ventas.',
    challengeLabel: 'Desafío',
    challenges: ['Modificar el backend requería comprender previamente qué consumía cada sistema porque un cambio podía afectar ambos proyectos.'],
    participation: [
      'Revisar qué endpoint utilizaba la aplicación.',
      'Analizar dependencias.',
      'Consultar al equipo del otro sistema cuando un cambio podía afectarlo.',
      'Recuperar contexto con desarrolladores que habían trabajado anteriormente en esa parte.',
      'Validar el comportamiento después de los cambios.',
      'Participar en la revisión y reestructuración de endpoints mal implementados o duplicados.',
      'Apoyar la detección de un problema relacionado con base de datos.',
    ],
    process: ['Identificar', 'Investigar', 'Consultar', 'Modificar', 'Probar', 'Validar'],
    flow: ['Sistema contable', 'API compartida', 'Sistema de ventas'],
    result: 'Se pudieron introducir cambios y correcciones manteniendo control sobre las dependencias de ambos sistemas.',
    tools: ['API'],
  },
  {
    number: '03',
    title: 'Evolución de sistema de ventas legado',
    status: 'case',
    group: 'DESARROLLO',
    category: 'DESARROLLO · LEGACY · REFACTORING',
    summary: 'Investigación, mantenimiento y evolución de una aplicación existente con dependencias compartidas.',
    context: 'Sistema de ventas existente dentro del mismo ecosistema, con código previo y dependencias compartidas que requerían investigación antes de modificarlo.',
    challengeLabel: 'Desafío',
    challenges: ['Comprender una solución que no había sido construida completamente por mí y entender decisiones anteriores antes de continuar desarrollándola.'],
    participation: [
      'Investigación de código existente.',
      'Comprensión de flujos.',
      'Corrección de funcionalidades.',
      'Refactorización.',
      'Desarrollo de nuevas funcionalidades.',
      'Integración con API compartida.',
      'Validaciones para evitar efectos sobre el otro sistema.',
      'Debugging y pruebas.',
    ],
    result: 'Se logró continuar la evolución del sistema manteniendo compatibilidad con las dependencias existentes.',
    tools: ['APIs', 'Backend', 'Frontend', 'Refactoring', 'Debugging', 'Testing'],
  },
  {
    number: '04',
    title: 'Remediación de infraestructura AWS',
    status: 'case',
    group: 'CLOUD & CIBERSEGURIDAD',
    category: 'CLOUD · CIBERSEGURIDAD · COORDINACIÓN',
    summary: 'Ownership operativo y coordinación de la remediación de un hallazgo persistente relacionado con AMI e instancias AWS.',
    subtitle: 'Una vulnerabilidad persistente que requería mirar más allá de la alerta.',
    context: 'Dentro del ciclo semanal de vulnerabilidades permanecía abierto un hallazgo alto asociado con una AMI clonada y las instancias AWS creadas desde ella. La condición se reproducía y entraba en conflicto con políticas internas.',
    objective: 'Eliminar el hallazgo persistente sin perder control sobre el impacto del cambio para Infraestructura, CLOC, ServiceNow y los demás equipos involucrados.',
    scope: [
      'Dirigir el seguimiento operativo, priorización, escalación y validación del caso; no ejecutar de forma individual todos los cambios de infraestructura.',
      'Mantener responsables, evidencias, dependencias, políticas, riesgos y pasos de cambio trazables hasta el cierre.',
    ],
    strategy: [
      'Correlacionar evidencia de Brinqa y AWS para localizar la condición heredada por la AMI.',
      'Coordinar análisis de impacto, planificación del cambio, remediación y comprobación posterior.',
      'Gestionar el ticket, bloqueos, evidencias y aprobaciones hasta validar que el hallazgo dejara de estar activo.',
    ],
    coordination: ['Equipo CLOC', 'Infraestructura', 'ServiceNow', 'Seguridad Informática', 'Desarrollo'],
    challengeLabel: 'Hallazgo',
    challenges: [
      'Mediante Brinqa y AWS se identificó que una AMI clonada heredaba una condición que no se adaptaba a las políticas de la empresa.',
      'Al crearse nuevas instancias desde esa imagen, la condición problemática se reproducía.',
      'También se analizó el comportamiento de las instancias elásticas relacionadas.',
    ],
    participation: ['Coordinación operativa, priorización, escalación, evidencias y validación de la remediación.'],
    result: 'La AMI fue adaptada a las políticas correspondientes y se eliminaron las instancias elásticas involucradas. Tras la validación, el hallazgo persistente restante pasó a 0 y el caso pudo cerrarse.',
    tools: ['AWS', 'Brinqa', 'Jira', 'ServiceNow', 'Vulnerability Management'],
  },
  {
    number: '05',
    title: 'Gestión de vulnerabilidades',
    status: 'case',
    group: 'CLOUD & CIBERSEGURIDAD',
    category: 'CIBERSEGURIDAD · OPERACIONES',
    summary: 'Gestión del ciclo semanal de vulnerabilidades, SLA, criticidad, ambientes, remediación, evidencias y cierre.',
    context: 'Brinqa ejecutaba scans durante la semana y generaba hallazgos de distinta criticidad en QA, producción y otros ambientes. En periodos de mayor volumen, el ciclo podía comenzar con aproximadamente 300–400 vulnerabilidades.',
    objective: 'Clasificar, priorizar y llevar las remediaciones correspondientes a resolución antes del cierre semanal del viernes cuando fuera posible dentro del SLA establecido.',
    scope: [
      'Supervisar vulnerabilidades abiertas y cerradas, criticidad, ambiente, riesgo, cumplimiento semanal, SLA y KPIs.',
      'Gestionar operativamente al equipo CLOC de aproximadamente 12 especialistas, distribuyendo prioridades y escalando bloqueos o dependencias.',
    ],
    strategy: [
      'Recuperar un plan de remediación que había perdido continuidad e incorporar observaciones del equipo CLOC.',
      'Establecer coordinación semanal desde el lunes, priorizando cambios según riesgo y ambiente.',
      'Contrastar Brinqa con AWS y evidencias de Infraestructura antes de validar la remediación o descartar un falso positivo.',
      'Coordinar un proceso que incorporó automatización mediante AWS Lambda para actualizaciones recurrentes.',
    ],
    coordination: ['CLOC', 'Infraestructura', 'Seguridad Informática', 'ServiceNow', 'Responsables técnicos según el hallazgo'],
    challengeLabel: 'Desafío',
    challenges: [],
    participation: ['Gestión semanal de prioridades, responsables, SLA, evidencias, escalaciones, validación y cierre.'],
    process: ['Brinqa', 'Revisión del hallazgo', 'AWS / Infraestructura', 'Real o falso positivo', 'Ticket + evidencia', 'Remediación', 'Validación', 'Cierre'],
    result: 'En periodos de alto volumen, los ciclos partían de aproximadamente 300–400 hallazgos y llegaban habitualmente a alrededor de 1 pendiente al cierre semanal. Cada cierre se validaba con evidencia y comprobación posterior de que el hallazgo ya no permaneciera activo.',
    tools: ['Brinqa', 'AWS', 'AWS Lambda', 'Jira', 'ServiceNow', 'Vulnerability Management'],
  },
  {
    number: '06',
    title: 'Registro & OTP multinacional',
    status: 'case',
    group: 'GESTIÓN TECNOLÓGICA',
    category: 'GESTIÓN TECNOLÓGICA · QA · INTEGRACIONES',
    summary: 'Análisis y validación de un flujo de registro y OTP para República Dominicana y Guatemala.',
    metaLabel: 'Mercados',
    meta: 'República Dominicana · Guatemala',
    context: 'Un ecosistema web requería que los usuarios solicitaran un código OTP antes de completar su registro.',
    objective: 'Restablecer y validar el flujo de registro y OTP para República Dominicana y Guatemala hasta obtener aprobación para producción.',
    scope: [
      'Coordinar troubleshooting, pruebas, defectos, bloqueos, correcciones y validación entre sistemas y equipos distribuidos.',
      'Mantener responsabilidad sobre el seguimiento técnico hasta la aprobación del flujo.',
    ],
    strategy: [
      'Comparar la implementación con la documentación y probar el comportamiento del OTP en ambos mercados.',
      'Aislar diferencias entre la web, API de registro y servicio de envío; documentar hallazgos y coordinar correcciones.',
      'Ejecutar la validación funcional final después de los cambios.',
    ],
    coordination: ['Desarrollo web', 'Negocio', 'Equipos de República Dominicana y Guatemala', 'Desarrolladores terceros en Filipinas · coordinación técnica en inglés'],
    challengeLabel: 'Problema',
    challenges: [
      'El comportamiento no era consistente entre República Dominicana y Guatemala.',
      'Para Guatemala existía un problema de comunicación/envío del OTP entre los sistemas integrados.',
      'Sin OTP, un nuevo cliente no podía completar su registro.',
    ],
    flow: ['Usuario', 'Web', 'API de registro', 'Servicio/API de envío', 'OTP', 'Registro'],
    participation: ['Coordinación internacional, testing, troubleshooting, gestión de terceros y seguimiento hasta producción.'],
    result: 'Después de las correcciones y pruebas, se validó el funcionamiento del flujo y se dio el visto bueno para la salida a producción.',
    tools: ['QA', 'APIs', 'OTP', 'Jira', 'English technical communication'],
  },
  {
    number: '07',
    title: 'Mapeo de ecosistema tecnológico',
    status: 'case',
    group: 'GESTIÓN TECNOLÓGICA',
    category: 'GESTIÓN · ANÁLISIS · DOCUMENTACIÓN',
    summary: 'Estructuración de la primera fase de un mapeo tecnológico para dar visibilidad, continuidad y criterios de priorización.',
    context: 'Una iniciativa de mapeo tecnológico necesitaba recuperar visibilidad sobre proyectos, sistemas, responsables, dependencias y problemáticas distribuidas entre múltiples equipos.',
    objective: 'Convertir información dispersa en una base centralizada y utilizable para continuidad, análisis y toma de decisiones.',
    scope: [
      'Estructurar la primera fase, coordinar responsables y establecer seguimiento sin atribuirse la dirección individual de todas las reuniones.',
      'Dar visibilidad a stakeholders sobre avances, riesgos, bloqueos y estado de iniciativas.',
    ],
    strategy: [
      'Consolidar responsables, canales de comunicación, dependencias, problemáticas y documentación en Confluence.',
      'Asociar diagramas y organizar la información por proyecto o sistema.',
      'Crear una escala y modelo de métricas para analizar, comparar y priorizar iniciativas según sus problemáticas.',
    ],
    coordination: ['Responsables de proyectos y sistemas', 'Equipos técnicos', 'Stakeholders', 'Supervisión operativa'],
    challengeLabel: 'Desafío',
    challenges: [],
    participation: ['Estructuración del proceso, coordinación de responsables, documentación centralizada y diseño del modelo de métricas.'],
    result: 'La primera fase quedó estructurada con proyectos y sistemas documentados, responsables y canales definidos, problemáticas centralizadas, diagramas asociados y un modelo de métricas disponible para continuar el análisis y la priorización.',
    tools: ['Confluence', 'Jira', 'Documentation', 'Diagrams', 'Coordination', 'Metrics'],
  },
  {
    number: '02',
    title: 'Cyber Risk Intelligence',
    status: 'planned',
    stack: ['Power BI', 'Python', 'Ciberseguridad'],
    description: 'Proyecto de portafolio por desarrollar.',
  },
  {
    number: '03',
    title: 'Data & BI',
    status: 'planned',
    stack: ['Power BI', 'Análisis'],
    description: 'Proyecto de portafolio por desarrollar.',
  },
  {
    number: '04',
    title: 'Seguridad aplicada',
    status: 'planned',
    stack: ['Ciberseguridad', 'Investigación'],
    description: 'Proyecto de portafolio por desarrollar.',
  },
];

export const skillsEs: SkillGroup[] = [
  {
    title: 'Frontend',
    level: 'professional',
    items: ['React', 'TypeScript', 'JavaScript', 'HTML5', 'CSS3', 'SASS/SCSS', 'Responsive', 'Bootstrap', 'Tailwind', 'Material'],
  },
  {
    title: 'Backend & APIs',
    level: 'professional',
    items: ['Node.js', 'NestJS', 'REST APIs', 'GraphQL', 'Prisma', 'Validaciones', 'Versionamiento', 'Error handling'],
  },
  {
    title: 'Datos',
    level: 'professional',
    items: ['MySQL', 'SQL Server', 'MongoDB', 'Firebase', 'SQL', 'JOINs', 'Subqueries', 'CRUD', 'Modelado'],
  },
  {
    title: 'Gestión & Delivery',
    level: 'professional',
    items: ['Jira', 'Xray', 'ServiceNow', 'Scrum', 'Agile', 'SDLC', 'Incident Management', 'Reporting', 'Stakeholders'],
  },
  {
    title: 'Cloud & Operaciones',
    level: 'professional',
    items: ['AWS Monitoring', 'AWS Lambda reviews', 'Troubleshooting', 'Windows', 'Linux', 'Networking'],
  },
  {
    title: 'Ciberseguridad',
    level: 'practical',
    items: ['Vulnerability review', 'ISO 27001', 'OWASP Top 10', 'IAM básico', 'Autenticación', 'Tokens', 'Sesiones', 'Encriptación'],
  },
  {
    title: 'Data & BI',
    level: 'practical',
    items: ['Power BI Nivel I', 'Power BI Nivel II', 'Análisis de datos'],
  },
  {
    title: 'Formación complementaria',
    level: 'complementary',
    items: ['Ethical Hacking', 'Criptografía', 'Principios de Ciberseguridad', 'GitHub Actions', 'CI/CD conceptual'],
  },
];

export const educationEs: EducationItem[] = [
  {
    title: 'Ingeniería en Sistemas de Información',
    institution: 'Universidad Internacional de las Américas (UIA)',
    year: '2025',
    note: 'Cum Laude con Honores',
  },
  {
    title: 'Especialización en Ciberseguridad',
    institution: 'Universidad Fidélitas',
    year: '2025',
    note: '96 horas',
  },
  {
    title: 'Análisis de Datos con Power BI — Nivel II',
    institution: 'Universidad de Costa Rica (UCR)',
    year: '2025',
  },
  {
    title: 'Análisis de Datos con Power BI — Nivel I',
    institution: 'Universidad de Costa Rica (UCR)',
    year: '2025',
  },
  {
    title: 'Técnico Medio en Soporte de Tecnologías de Información',
    institution: 'Colegio Técnico Profesional de Pavas',
    year: '2019',
  },
];

export const certificationsEs = [
  'Scrum Fundamentals Certified — VMEdu · 2022',
  'React Development — Udemy · 2023',
  'Professional Communication in English — Rocket Girls · 2025',
  'Advanced Conversational English — Academia Europea · 2021',
  'Ethical Hacking — Universidad Fidélitas · 2025',
  'Criptografía — Universidad Fidélitas · 2025',
  'Principios de Ciberseguridad — Universidad Fidélitas · 2025',
];
