import type { BookDefinition, EducationItem, ExperienceItem, ProjectItem, SkillGroup } from '../types/content';

export const homeEs = {
  prologue: 'PRÓLOGO / 00',
  title: 'El Archivo Celestial',
  description:
    'Tecnología, investigación y propósito. Una colección de capítulos construidos con curiosidad, disciplina y la decisión de ir siempre un poco más allá.',
  cta: 'EXPLORAR EL ARCHIVO',
  quote: '“Siempre hay algo nuevo que descubrir.”',
} as const;

export const booksEs: BookDefinition[] = [
  { id: 'about', number: '01', title: 'Sobre mí', subtitle: 'Historia y propósito', tone: 'cream' },
  { id: 'experience', number: '02', title: 'Experiencia', subtitle: 'Trayectoria profesional', tone: 'terracotta' },
  { id: 'projects', number: '03', title: 'Proyectos', subtitle: 'Ideas que construyo', tone: 'charcoal' },
  { id: 'skills', number: '04', title: 'Habilidades', subtitle: 'Conocimiento y método', tone: 'sand' },
  { id: 'education', number: '05', title: 'Formación', subtitle: 'Aprendizaje y disciplina', tone: 'copper' },
  { id: 'contact', number: '06', title: 'Contacto', subtitle: 'El siguiente capítulo', tone: 'brown' },
];

export const aboutEs = {
  chapter: 'CAPÍTULO I',
  title: 'Sobre mí',
  intro:
    'Ingeniera en Sistemas con una forma de pensar estructurada, curiosa e imaginativa. Me motiva la tecnología porque siempre hay algo nuevo que aprender, investigar o resolver.',
  second:
    'Prefiero entender un problema a fondo, explorar alternativas y después construir una solución con intención.',
  traits: 'ENTRE LÓGICA Y CONSTELACIONES',
  traitsBody: 'Observo. Investigo. Conecto ideas. Construyo.',
  quote: '“No sigo un mapa. Aprendo a leer las estrellas.”',
  quoteBody:
    'La tecnología cambia constantemente. Mi forma de avanzar es entender, investigar y construir mi propio camino.',
  methodTitle: 'Entender antes de construir',
  method: [
    ['01', 'ENTENDER', 'Comprender el problema y el contexto antes de decidir.'],
    ['02', 'INVESTIGAR', 'Comparar alternativas, riesgos y posibilidades.'],
    ['03', 'ORGANIZAR', 'Transformar información en un plan claro y ejecutable.'],
    ['04', 'RESOLVER', 'Construir, probar, ajustar y aprender del resultado.'],
  ],
};

export const experienceEs: ExperienceItem[] = [
  {
    period: 'Oct 2025 — Jun 2026',
    role: 'Técnico',
    company: 'Componentes El Orbe',
    focus: 'Coordinación técnica, operaciones TI, ciberseguridad, AWS, incident management y mejora de procesos.',
    points: [
      'Coordinación y seguimiento de workstreams de ciberseguridad, incidentes y remediación.',
      'Trazabilidad de tareas, defectos, hallazgos, bloqueos y riesgos mediante Jira y Xray.',
      'Monitoreo de servicios AWS, continuidad operativa y escalamiento.',
      'Auditorías técnicas y operativas alineadas con principios de ISO 27001.',
      'Soporte al SDLC, pruebas, cambios, releases e implementaciones.',
    ],
    tools: ['Jira', 'Xray', 'AWS', 'ServiceNow', 'ISO 27001', 'SDLC'],
  },
  {
    period: 'Ene 2023 — Dic 2024',
    role: 'Ingeniera en Sistemas enfocada en Desarrollo Web',
    company: 'Tavuel',
    focus: 'Desarrollo web end-to-end, mantenimiento, integraciones y soporte a cambios.',
    points: [
      'Aproximadamente tres proyectos de distinto tamaño, incluyendo proyecto desde cero, aplicación existente y sistema legado.',
      'React y TypeScript en frontend; Node.js/NestJS, REST APIs, GraphQL y Prisma en backend.',
      'Integraciones con Google APIs/Maps, Firebase, correo, ERP y API de Hacienda.',
      'MySQL, SQL Server, MongoDB y Firebase.',
      'Testing, debugging, Git/GitHub, Pull Requests, code review y validación posterior a deployments.',
    ],
    tools: ['React', 'TypeScript', 'Node.js', 'NestJS', 'SQL', 'Git/GitHub'],
  },
  {
    period: '2019',
    role: 'Pasante de Soporte Técnico',
    company: 'Clínica UNIBE',
    focus: 'Soporte presencial y remoto, hardware, software, red y continuidad operativa.',
    points: [],
    tools: ['Windows', 'Networking', 'Hardware'],
  },
  {
    period: '2018',
    role: 'Pasante de Soporte TI',
    company: 'Servicio Fitosanitario del Estado',
    focus: 'Configuración de red, mantenimiento de equipos, UPS y diagnóstico de hardware.',
    points: [],
    tools: ['Networking', 'Hardware', 'UPS'],
  },
];

export const projectsIntroEs = {
  chapter: 'CAPÍTULO III',
  title: 'Casos & Proyectos',
  lead: 'No solo lo que construí.\nLos problemas que tuve que entender para construirlo.',
  description:
    'Una selección de desarrollo, integraciones, cloud, ciberseguridad y gestión tecnológica aplicada a situaciones reales.',
} as const;

export const projectsEs: ProjectItem[] = [
  {
    number: '01',
    title: 'Plataforma de ventas end-to-end',
    status: 'case',
    group: 'DESARROLLO',
    category: 'DESARROLLO · FULL STACK · EXPERIENCIA PROFESIONAL',
    summary: 'Desarrollo de una plataforma de ventas con autenticación, administración, estadísticas, APIs y proceso completo de pago.',
    context: 'Desarrollo de una plataforma de ventas con flujo completo desde autenticación y administración de usuarios hasta procesamiento de ventas, estadísticas y pasarela de pago.',
    challengeLabel: 'Desafíos',
    challenges: [
      'Mantener el estado de una compra ante pérdida de conexión, recarga de página u otras interrupciones durante el pago.',
      'Controlar sesión y tokens para evitar pérdida de progreso durante procesos extensos.',
      'Trabajar directamente en la lógica de la pasarela de pago.',
      'Crear o modificar endpoints cuando era necesario.',
      'Analizar endpoints duplicados o incorrectamente implementados.',
      'Crear gráficos administrativos utilizando información del sistema y adaptarlos a diferentes diseños.',
      'Resolver un problema de frontend en iOS que afectaba una funcionalidad del pago.',
      'Adaptar plantillas de correo para Gmail, Outlook, iOS y otros clientes.',
      'Apoyar la detección de un problema relacionado con base de datos.',
    ],
    participation: ['Frontend + Backend + APIs + Debugging + Testing + Integraciones.'],
    result: 'Se resolvieron problemas críticos del flujo de compra, autenticación e integración, permitiendo mantener la continuidad del proceso hasta el pago y la operación de los módulos administrativos.',
    tools: ['React', 'TypeScript', 'Node.js', 'APIs', 'Auth/Tokens', 'Payments', 'SQL', 'Email'],
  },
  {
    number: '02',
    title: 'Sistema contable + API compartida',
    status: 'case',
    group: 'DESARROLLO',
    category: 'DESARROLLO · INTEGRACIÓN DE SISTEMAS',
    summary: 'Cambios en un sistema contable conectado a una API compartida con una aplicación de ventas.',
    context: 'Una aplicación contable pertenecía a un ecosistema donde una misma API también era utilizada por otro sistema de ventas.',
    challengeLabel: 'Desafío',
    challenges: ['Modificar el backend requería comprender previamente qué consumía cada sistema porque un cambio podía afectar ambos proyectos.'],
    participation: [
      'Revisar qué endpoint utilizaba la aplicación.',
      'Analizar dependencias.',
      'Consultar al equipo del otro sistema cuando un cambio podía afectarlo.',
      'Recuperar contexto con desarrolladores que habían trabajado anteriormente en esa parte.',
      'Validar el comportamiento después de los cambios.',
      'Participar en la revisión y reestructuración de endpoints mal implementados o duplicados.',
      'Apoyar la detección de un problema relacionado con base de datos.',
    ],
    process: ['Identificar', 'Investigar', 'Consultar', 'Modificar', 'Probar', 'Validar'],
    flow: ['Sistema contable', 'API compartida', 'Sistema de ventas'],
    result: 'Se pudieron introducir cambios y correcciones manteniendo control sobre las dependencias de ambos sistemas.',
    tools: ['API'],
  },
  {
    number: '03',
    title: 'Evolución de sistema de ventas legado',
    status: 'case',
    group: 'DESARROLLO',
    category: 'DESARROLLO · LEGACY · REFACTORING',
    summary: 'Investigación, mantenimiento y evolución de una aplicación existente con dependencias compartidas.',
    context: 'Sistema de ventas existente dentro del mismo ecosistema, con código previo y dependencias compartidas que requerían investigación antes de modificarlo.',
    challengeLabel: 'Desafío',
    challenges: ['Comprender una solución que no había sido construida completamente por mí y entender decisiones anteriores antes de continuar desarrollándola.'],
    participation: [
      'Investigación de código existente.',
      'Comprensión de flujos.',
      'Corrección de funcionalidades.',
      'Refactorización.',
      'Desarrollo de nuevas funcionalidades.',
      'Integración con API compartida.',
      'Validaciones para evitar efectos sobre el otro sistema.',
      'Debugging y pruebas.',
    ],
    result: 'Se logró continuar la evolución del sistema manteniendo compatibilidad con las dependencias existentes.',
    tools: ['APIs', 'Backend', 'Frontend', 'Refactoring', 'Debugging', 'Testing'],
  },
  {
    number: '04',
    title: 'Remediación de infraestructura AWS',
    status: 'case',
    group: 'CLOUD & CIBERSEGURIDAD',
    category: 'CLOUD · CIBERSEGURIDAD · COORDINACIÓN',
    summary: 'Investigación y seguimiento de una vulnerabilidad persistente relacionada con AMI e instancias AWS.',
    subtitle: 'Una vulnerabilidad persistente que requería mirar más allá de la alerta.',
    context: 'Durante el monitoreo apareció repetidamente una vulnerabilidad alta asociada con infraestructura AWS. Aunque el hallazgo era conocido desde hacía tiempo y se consideraba de impacto limitado, se profundizó en el análisis porque entraba en conflicto con políticas internas.',
    challengeLabel: 'Hallazgo',
    challenges: [
      'Mediante Brinqa y AWS se identificó que una AMI clonada heredaba una condición que no se adaptaba a las políticas de la empresa.',
      'Al crearse nuevas instancias desde esa imagen, la condición problemática se reproducía.',
      'También se analizó el comportamiento de las instancias elásticas relacionadas.',
    ],
    participation: [
      'Detectar y reportar nuevamente el problema.',
      'Analizar información en Brinqa y AWS.',
      'Recopilar evidencia y pruebas.',
      'Documentar el comportamiento observado.',
      'Crear y dar seguimiento a tickets.',
      'Coordinar reuniones.',
      'Dar seguimiento a infraestructura y desarrollo.',
      'Acompañar planificación, implementación y validación.',
      'Apoyar con criterios en análisis económico cuando aparecían inconsistencias.',
      'Comprobar el resultado antes del cierre.',
    ],
    result: 'Se eliminaron las instancias elásticas involucradas y la AMI fue adaptada a las políticas correspondientes. El proceso se completó correctamente y quedó preparado para continuar con el siguiente equipo.',
    tools: ['AWS', 'Brinqa', 'Jira', 'Vulnerability Management'],
  },
  {
    number: '05',
    title: 'Gestión de vulnerabilidades',
    status: 'case',
    group: 'CLOUD & CIBERSEGURIDAD',
    category: 'CIBERSEGURIDAD · OPERACIONES',
    summary: 'Análisis, seguimiento y validación de vulnerabilidades desde detección hasta cierre.',
    context: 'Revisión continua de vulnerabilidades relacionadas principalmente con versionamiento, actualizaciones y configuración.',
    challengeLabel: 'Desafío',
    challenges: [],
    participation: [
      'Analizar cada hallazgo.',
      'Contrastar Brinqa con evidencia de infraestructura.',
      'Revisar información de AWS.',
      'Determinar si el comportamiento correspondía a vulnerabilidad real o posible falso positivo.',
      'Dar seguimiento al equipo responsable.',
      'Revisar evidencia entregada por infraestructura.',
      'Analizar la explicación documentada en el ticket.',
      'Comprobar posteriormente el estado del hallazgo.',
      'Tomar el criterio de cierre con base en evidencia y corrección realizada.',
    ],
    process: ['Brinqa', 'Revisión del hallazgo', 'AWS / Infraestructura', 'Real o falso positivo', 'Ticket + evidencia', 'Remediación', 'Validación', 'Cierre'],
    result: 'Los casos se acompañaban desde análisis hasta validación posterior a la remediación, comprobando que el hallazgo ya no permaneciera activo antes de cerrarlo.',
    tools: ['Brinqa', 'AWS', 'Jira', 'Vulnerability Management'],
  },
  {
    number: '06',
    title: 'Registro & OTP multinacional',
    status: 'case',
    group: 'GESTIÓN TECNOLÓGICA',
    category: 'GESTIÓN TECNOLÓGICA · QA · INTEGRACIONES',
    summary: 'Análisis y validación de un flujo de registro y OTP para República Dominicana y Guatemala.',
    metaLabel: 'Mercados',
    meta: 'República Dominicana · Guatemala',
    context: 'Un ecosistema web requería que los usuarios solicitaran un código OTP antes de completar su registro.',
    challengeLabel: 'Problema',
    challenges: [
      'El comportamiento no era consistente entre República Dominicana y Guatemala.',
      'Para Guatemala existía un problema de comunicación/envío del OTP entre los sistemas integrados.',
      'Sin OTP, un nuevo cliente no podía completar su registro.',
    ],
    flow: ['Usuario', 'Web', 'API de registro', 'Servicio/API de envío', 'OTP', 'Registro'],
    participation: [
      'Analizar las distintas partes del ecosistema.',
      'Revisar el sistema web.',
      'Comparar implementación contra documentación.',
      'Identificar diferencias y elementos que requerían revisión.',
      'Ejecutar pruebas de OTP en ambos países.',
      'Documentar hallazgos.',
      'Comunicar resultados.',
      'Coordinar con desarrollo web.',
      'Coordinar con el equipo responsable del API integrado.',
      'Acompañar las correcciones.',
      'Realizar la validación funcional final.',
    ],
    result: 'Después de las correcciones y pruebas, se validó el funcionamiento del flujo y se dio el visto bueno para la salida a producción.',
    tools: ['QA', 'APIs', 'OTP'],
  },
  {
    number: '07',
    title: 'Mapeo de ecosistema tecnológico',
    status: 'case',
    group: 'GESTIÓN TECNOLÓGICA',
    category: 'GESTIÓN · ANÁLISIS · DOCUMENTACIÓN',
    summary: 'Primera fase de organización y documentación de sistemas y problemáticas de un ecosistema empresarial.',
    context: 'Participación en la primera fase de una iniciativa destinada a mapear sistemas y problemáticas dentro de un ecosistema tecnológico empresarial.',
    challengeLabel: 'Desafío',
    challenges: [],
    participation: [
      'Conocer y organizar el cronograma de participantes.',
      'Dar seguimiento a disponibilidad y avances.',
      'Coordinar las primeras reuniones relacionadas con mapeos prioritarios.',
      'Registrar respuestas y problemáticas.',
      'Resolver consultas cuando correspondía.',
      'Documentar información en Confluence.',
      'Trabajar con diagramas asociados.',
      'Organizar la información obtenida.',
      'Crear una tabla de estadísticas/métricas para analizar proyectos según sus problemáticas.',
    ],
    result: 'La primera etapa quedó organizada con reuniones iniciales coordinadas, respuestas documentadas por problemática y una estructura de métricas disponible para continuar el análisis.',
    tools: ['Confluence', 'Documentation', 'Diagrams', 'Coordination', 'Metrics'],
  },
  {
    number: '02',
    title: 'Cyber Risk Intelligence',
    status: 'planned',
    stack: ['Power BI', 'Python', 'Ciberseguridad'],
    description: 'Proyecto de portafolio por desarrollar.',
  },
  {
    number: '03',
    title: 'Data & BI',
    status: 'planned',
    stack: ['Power BI', 'Análisis'],
    description: 'Proyecto de portafolio por desarrollar.',
  },
  {
    number: '04',
    title: 'Seguridad aplicada',
    status: 'planned',
    stack: ['Ciberseguridad', 'Investigación'],
    description: 'Proyecto de portafolio por desarrollar.',
  },
];

export const skillsEs: SkillGroup[] = [
  {
    title: 'Frontend',
    level: 'professional',
    items: ['React', 'TypeScript', 'JavaScript', 'HTML5', 'CSS3', 'SASS/SCSS', 'Responsive', 'Bootstrap', 'Tailwind', 'Material'],
  },
  {
    title: 'Backend & APIs',
    level: 'professional',
    items: ['Node.js', 'NestJS', 'REST APIs', 'GraphQL', 'Prisma', 'Validaciones', 'Versionamiento', 'Error handling'],
  },
  {
    title: 'Datos',
    level: 'professional',
    items: ['MySQL', 'SQL Server', 'MongoDB', 'Firebase', 'SQL', 'JOINs', 'Subqueries', 'CRUD', 'Modelado'],
  },
  {
    title: 'Gestión & Delivery',
    level: 'professional',
    items: ['Jira', 'Xray', 'ServiceNow', 'Scrum', 'Agile', 'SDLC', 'Incident Management', 'Reporting', 'Stakeholders'],
  },
  {
    title: 'Cloud & Operaciones',
    level: 'professional',
    items: ['AWS Monitoring', 'AWS Lambda reviews', 'Troubleshooting', 'Windows', 'Linux', 'Networking'],
  },
  {
    title: 'Ciberseguridad',
    level: 'practical',
    items: ['Vulnerability review', 'ISO 27001', 'OWASP Top 10', 'IAM básico', 'Autenticación', 'Tokens', 'Sesiones', 'Encriptación'],
  },
  {
    title: 'Data & BI',
    level: 'practical',
    items: ['Power BI Nivel I', 'Power BI Nivel II', 'Análisis de datos'],
  },
  {
    title: 'Formación complementaria',
    level: 'complementary',
    items: ['Ethical Hacking', 'Criptografía', 'Principios de Ciberseguridad', 'GitHub Actions', 'CI/CD conceptual'],
  },
];

export const educationEs: EducationItem[] = [
  {
    title: 'Ingeniería en Sistemas de Información',
    institution: 'Universidad Internacional de las Américas (UIA)',
    year: '2025',
    note: 'Cum Laude con Honores',
  },
  {
    title: 'Especialización en Ciberseguridad',
    institution: 'Universidad Fidélitas',
    year: '2025',
    note: '96 horas',
  },
  {
    title: 'Análisis de Datos con Power BI — Nivel II',
    institution: 'Universidad de Costa Rica (UCR)',
    year: '2025',
  },
  {
    title: 'Análisis de Datos con Power BI — Nivel I',
    institution: 'Universidad de Costa Rica (UCR)',
    year: '2025',
  },
  {
    title: 'Técnico Medio en Soporte de Tecnologías de Información',
    institution: 'Colegio Técnico Profesional de Pavas',
    year: '2019',
  },
];

export const certificationsEs = [
  'Scrum Fundamentals Certified — VMEdu · 2022',
  'React Development — Udemy · 2023',
  'Professional Communication in English — Rocket Girls · 2025',
  'Advanced Conversational English — Academia Europea · 2021',
  'Ethical Hacking — Universidad Fidélitas · 2025',
  'Criptografía — Universidad Fidélitas · 2025',
  'Principios de Ciberseguridad — Universidad Fidélitas · 2025',
];
